---
- name: Install Jenkins and dependencies
  hosts: jenkins
  become: yes
  tasks:
    - name: Update apt cache
      apt: { update_cache: yes }

    - name: Install Java and Maven
      apt: { name: ['openjdk-11-jdk', 'maven'], state: present }

    - name: Add Jenkins repository key
      apt_key: { url: https://pkg.jenkins.io/debian-stable/jenkins.io.key, state: present }

    - name: Add Jenkins repository
      apt_repository: { repo: 'deb https://pkg.jenkins.io/debian-stable binary/ ', state: present }

    - name: Install Jenkins
      apt: { name: jenkins, state: present }
      notify: Start Jenkins

  handlers:
    - name: Start Jenkins
      service: { name: jenkins, state: started, enabled: yes }