---
- name: Install SonarQube using Docker
  hosts: sonarqube
  become: yes
  tasks:
    - name: Install Docker prerequisites and Docker
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'docker-ce']
        state: present
        update_cache: yes
      
    - name: Add Docker GPG key
      apt_key: { url: https://download.docker.com/linux/ubuntu/gpg, state: present }

    - name: Add Docker repository
      apt_repository: { repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable', state: present }

    - name: Add ubuntu user to docker group
      user: { name: ubuntu, groups: docker, append: yes }

    - name: Start and enable Docker service
      service: { name: docker, state: started, enabled: yes }

    - name: Increase virtual memory for Elasticsearch
      sysctl: { name: vm.max_map_count, value: '262144', state: present, reload: yes }

    - name: Run SonarQube container
      docker_container: { name: sonarqube, image: sonarqube:lts-community, state: started, restart_policy: always, ports: "9000:9000" }